### CREATE USER
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "carol",
    "email": "carol@email.com",
    "password": "123456"
}

### LOGIN
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "carol@email.com" ,
   "password": "123456"
}

### CREATE POST
POST http://localhost:3003/post/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzNzVlZjE3LWJhNTEtNGI5Ni05YTEyLTlmYmE4ZmE5ODk3YSIsImlhdCI6MTY3NTIwNDY2NSwiZXhwIjoxNjc1MjA4MjY1fQ.VEwEGI3HL7C6w59IsYPkgsIcto9X6bYFTtlWM8QeoWs
Content-Type: application/json

{
    "photo": "http",
    "description": "Vendo filme",
    "type": "normal"
}

### GET POST BY ID
GET http://localhost:3003/post/3b6f67e9-48df-48d8-b41f-735c242d0601

### CREATE FRIENDSHIP
POST http://localhost:3003/friendship/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzNzVlZjE3LWJhNTEtNGI5Ni05YTEyLTlmYmE4ZmE5ODk3YSIsImlhdCI6MTY3NTIwNDY2NSwiZXhwIjoxNjc1MjA4MjY1fQ.VEwEGI3HL7C6w59IsYPkgsIcto9X6bYFTtlWM8QeoWs
Content-Type: application/json

{
    "friendId": "b055ff6c-bf5d-42d7-bd67-014c44f1460d"
}

### DELETE FRIENDSHIP
DELETE http://localhost:3003/friendship/delete/b055ff6c-bf5d-42d7-bd67-014c44f1460d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzNzVlZjE3LWJhNTEtNGI5Ni05YTEyLTlmYmE4ZmE5ODk3YSIsImlhdCI6MTY3NTIwNDY2NSwiZXhwIjoxNjc1MjA4MjY1fQ.VEwEGI3HL7C6w59IsYPkgsIcto9X6bYFTtlWM8QeoWs

### GET FEED
GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzNzVlZjE3LWJhNTEtNGI5Ni05YTEyLTlmYmE4ZmE5ODk3YSIsImlhdCI6MTY3NTIwNDY2NSwiZXhwIjoxNjc1MjA4MjY1fQ.VEwEGI3HL7C6w59IsYPkgsIcto9X6bYFTtlWM8QeoWs